Debug fixtures

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -168,12 +168,16 @@ jobs:
             exit 1
           fi
           cp "solutions/$SOL/be-openimis.json" "$BUILD_DIR/openimis.json"
-
+          echo "=== Contents of ${{ env.BUILD_DIR_BE }} ==="
+          ls -la $BUILD_DIR
+          echo "=== Contents of ${{ env.BUILD_DIR_BE }}/fixtures (should exist) ==="
+          ls -la $$BUILD_DIR/fixtures || echo "fixtures/ not found!"
+          
           echo "=== BE openimis.json for $SOL ==="
           cat "$BUILD_DIR/openimis.json"
           echo "=== END ==="
 
-          [ -d "solutions/$SOL/fixtures" ] && cp -r "solutions/$SOL/fixtures" "$BUILD_DIR/fixtures/" || echo "No fixtures"
+          [ -d "solutions/$SOL/fixtures" ] && cp -r "solutions/$SOL/fixtures" "$BUILD_DIR/" || echo "No fixtures"
 
           echo "BUILD_DIR_BE=$BUILD_DIR" >> $GITHUB_ENV
           echo "LOWER_SOL=$LOWER_SOL" >> $GITHUB_ENV
@@ -207,6 +211,15 @@ jobs:
           echo "LOWER_SOL=$LOWER_SOL" >> $GITHUB_ENV
           echo "TAG_FE=${{ env.TAG_PREFIX }}-$LOWER_SOL" >> $GITHUB_ENV
 
+      - name: Debug - List build context (BE)
+        if: matrix.be
+        run: |
+          echo "=== Contents of ${{ env.BUILD_DIR_BE }} ==="
+          ls -la ${{ env.BUILD_DIR_BE }}
+          echo "=== Contents of ${{ env.BUILD_DIR_BE }}/fixtures (should exist) ==="
+          ls -la ${{ env.BUILD_DIR_BE }}/fixtures || echo "fixtures/ not found!"
+            
+      
       # -------------------------------------------------
       # Build BE image → openimis-be:<tag>-<solution>
       # -------------------------------------------------
